export const SET_LOCATION = "SET_LOCATION";

export const FETCHING_LOCATION_START = "FETCHING_LOCATION_START";
export const FETCHING_LOCATION_SUCCESS = "FETCHING_LOCATION_SUCCESS";
export const FETCHING_LOCATION_FAILURE = "FETCHING_LOCATION_FAILURE";
